version: '3.8'
services:
  app:
    build:
      context: .
      target: production
    image: evently:production
    ports:
      - 3008:3008
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mongo:7.0.2
    volumes:
      - mongo-prod-data:/data/db
    environment:
      MONGO_DB_URL: $MONGO_DB_URL
volumes:
  mongo-prod-data:
