FROM --platform=$BUILDPLATFORM node:lts-alpine as base
WORKDIR /app
COPY package.json /
RUN npm install
EXPOSE 3008

FROM base as production
ENV NODE_ENV=production
RUN npm install
COPY . /app
CMD npm run dev

FROM base as dev
ENV NODE_ENV=development
COPY . /app
CMD node server.js