name: Event Management System

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        mongodb-version: ["6.0"]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      - name: Install dependencies
        run: |
          cd Backend
          npm i

      - name: Run tests
        env:
          SALT_ROUND: ${{ secrets.SALT_ROUND }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ACCESS_TOKEN_EXPIRY: 1d
          REFRESH_TOKEN_EXPIRY: 15d
          CI: true
        run: |
          cd Backend 
          npm run test

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ needs.run-tests.result == 'success' }} # Only deploy if tests pass
    steps:
      - name: Trigger deployment webhook
        run: curl -X GET -d '{}' ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}

  deploy-to-netlify:
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ needs.run-tests.result == 'success' }} # Only deploy if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd Evently
          npm install

      - name: Build
        run: |
          cd Evently
          npm run build

      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          cd Evently
          npx netlify-cli deploy --prod --dir=./build --message "${{ steps.commit_message.outputs.message }}"

  send-slack-notification:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          mention: "here"
          author_name: "GitHub Actions"
          fields: repo,message,commit,author,workflow,job,took
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
