name: Event Management System

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ["4.4"]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      - name: Install dependencies
        env:
          SALT_ROUND: ${{ secrets.SALT_ROUND }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ACCESS_TOKEN_EXPIRY: 1d
          REFRESH_TOKEN_EXPIRY: 15d
        run: |
          cd Backend
          npm i

      - name: Run tests
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          CI: true
        run: |
          cd Backend 
          npm run test

  send-slack-notification:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          mention: "here"
          author_name: "GitHub Actions"
          fields: repo,message,commit,author,workflow,job,took
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
