name: Event Management System
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        mongodb-version: ["6.0"]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 42069

      - name: Install dependencies
        run: |
          cd Backend
          npm ci

      - name: Run tests
        run: |
          cd Backend 
          npm run test
        env:
          CI: true

  send-slack-notification:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          mention: "here"
          author_name: "GitHub Actions"
          fields: repo,message,commit,author,workflow,job,took
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
