name: Event Management System

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        mongodb-version: ["6.0"]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      - name: Install dependencies
        run: |
          cd Backend
          npm i

      - name: Run tests
        env:
          SALT_ROUND: ${{ secrets.SALT_ROUND }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ACCESS_TOKEN_EXPIRY: 1d
          REFRESH_TOKEN_EXPIRY: 15d
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CI: true
        run: |
          cd Backend 
          npm run test

      - name: Upload action logs
        uses: actions/upload-artifact@v2
        with:
          name: action-logs
          path: ${{ github.workspace }}/Backend/path/to/logs

  send-action-logs-to-slack:
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ always() }}
    steps:
      - name: Download action logs artifact
        uses: actions/download-artifact@v2
        with:
          name: action-logs
          path: logs

      - name: Send Slack notification with logs
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          mention: "here"
          author_name: "GitHub Actions"
          fields: repo,message,commit,author,workflow,job,took
          files: logs/*
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
